config/routes.rb
Catfacts::Application.routes.draw do  root :to => 'facts#new'
  resources :facts do
    collection do
      post :deliver
    end
  end
end

app/models/fact.rb
class Fact < ActiveRecord::Base
  attr_accessible :body

  def deliver(phone)
    client = Twilio::REST::Client.new ENV['TWILIO_KEY'], ENV['TWILIO_TOKEN']
    client.account.sms.messages.create(
      :from => '+19086722841',
      :to => phone,
      :body => self.body
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  # GET /facts
  # GET /facts.json
  def index
    @facts = Fact.all

    respond_to do |format|
      format.xml { render xml: @facts }
      format.html # index.html.erb
      format.json { render json: @facts }
    end
  end

  # GET /facts/1
  # GET /facts/1.json
  def show
    @fact = Fact.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fact }
    end
  end

  # GET /facts/new
  # GET /facts/new.json
  def new
    @fact = Fact.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fact }
    end
  end

  # GET /facts/1/edit
  def edit
    @fact = Fact.find(params[:id])
  end

  # POST /facts
  # POST /facts.json
  def create
    @fact = Fact.new(params[:fact])

    respond_to do |format|
      if @fact.save
        format.html { redirect_to @fact, notice: 'Fact was successfully created.' }
        format.json { render json: @fact, status: :created, location: @fact }
      else
        format.html { render action: "new" }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /facts/1
  # PUT /facts/1.json
  def update
    @fact = Fact.find(params[:id])

    respond_to do |format|
      if @fact.update_attributes(params[:fact])
        format.html { redirect_to @fact, notice: 'Fact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1
  # DELETE /facts/1.json
  def destroy
    @fact = Fact.find(params[:id])
    @fact.destroy

    respond_to do |format|
      format.html { redirect_to facts_url }
      format.json { head :no_content }
    end
  end

  def deliver
    @fact = Fact.order("RANDOM()").first

    @fact.deliver(params[:phone])

    redirect_to fact_path(@fact), :notice => 'Sent!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_form.html.erb
<%= form_for(@fact) do |f| %>
  <% if @fact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
      <% @fact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing fact</h1>

<%= render 'form' %>

<%= link_to 'Show', @fact %> |
<%= link_to 'Back', facts_path %>

app/views/facts/index.html.erb
<h1>Listing facts</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @facts.each do |fact| %>
  <tr>
    <td><%= fact.body %></td>
    <td><%= link_to 'Show', fact %></td>
    <td><%= link_to 'Edit', edit_fact_path(fact) %></td>
    <td><%= link_to 'Destroy', fact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= form_tag deliver_facts_path do %>
  Phone: 
  <%= text_field_tag :phone %>
  <%= submit_tag %>
<%- end %>

<%= link_to 'New Fact', new_fact_path %>

app/views/facts/new.html.erb
<h1>New fact</h1>

<%= render 'form' %>

<%= link_to 'Back', facts_path %>

app/views/facts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @fact.body %>
</p>



<%= link_to 'Edit', edit_fact_path(@fact) %> |
<%= link_to 'Back', facts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catfacts</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>